### ISSUE TITLE
Support Windows 7 now?

### ISSUE THREAD

**Issue by KingJA** [cesarferreira/dryrun#97]
C:\Users\Administrator>gem install dryrun
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    f:/wxy/Ruby22-x64/bin/ruby.exe -r ./siteconf20171011-8072-bgmme0.rb extconf.
rb
checking for jni.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

My OS is Windows 7, I have installed DevKit, and add F:\wxy\Ruby22-x64\devkit\bin in PATH.
So, is this error because dryrun doesn't supprot Windows?

**Comment by luispereira** [comment]
Hi @KingJA, dryrun supports windows with gem version 2.3 or above, may I ask which gem version you are using?

**Comment by KingJA** [comment]
@luispereira Hi, luispereira, thanks for your reply.

here is my version of gem:
C:\Users\Administrator>ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
C:\Users\Administrator>gem -v
2.4.5.1

I am very interesting in **dryrun**.  :sob:

**Comment by huzipiaopiao** [comment]
Hello, I have the same problem, I have not used ruby, I do not know if it is ruby problem, the log is as follows：
C:\Users\Administrator>gem install dryrun
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/
c
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20171201-25908-1bpc4eq.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR=" clean
'make'  e

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR="
'make'  e
make failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-l
l-2.1.2 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0
/ruby-ll-2.1.2/gem_make.out

C:\Users\Administrator>ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

C:\Users\Administrator>gem -v
2.6.13

**Comment by prathamApp** [comment]
Even I am getting the above same error.

Fetching: bundler-1.16.1.gem (100%)
Successfully installed bundler-1.16.1
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: ansi-1.5.0.gem (100%)
Successfully installed ansi-1.5.0
Fetching: ruby-ll-2.1.2.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed ruby-ll-2.1.2
Fetching: oga-1.3.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed oga-1.3.1
Fetching: highline-1.7.10.gem (100%)
Successfully installed highline-1.7.10
Fetching: rjb-1.5.5.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rjb-1.5.5/ext
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180119-6364-1rez2ci.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:53:in `<main>': JAVA_HOME is not set. (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rjb-1.5.5 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rjb-1.5.5/gem_make.out

Inastalled both the ruby and ruby dev kit.....then also the same error..Any help??

**Comment by prathamApp** [comment]
installed both the ruby and ruby devkit....then also..?
Any Help

**Comment by luispereira** [comment]
@prathamApp  I would bet on this 
"JAVA_HOME is not set. (RuntimeError)"

**Comment by prathamApp** [comment]
But, being an android developer and having installed all sort of java versions and android sdk....
What else JAVA_HOME is needed to be set?

**Comment by prathamApp** [comment]
@luispereira set JAVA_HOME to C:\Program Files\Java\jdk1.8.0_161\bin......but the error persists as follows:

C:\>gem install dryrun
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rjb-1.5.5/ext
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180119-1512-dnb2m3.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:45:in `open': No such file or directory @ dir_initialize - C:\Program Files\Java\jdk1.8.0_161\bin\include (Errno::ENOENT)
        from extconf.rb:45:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rjb-1.5.5 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rjb-1.5.5/gem_make.out


..
Any help?

**Comment by luispereira** [comment]
@prathamApp Hi, I do believe there is something wrong with your devkit installation, I also dig some digging and found this https://github.com/oneclick/rubyinstaller/issues/288 and this
https://github.com/jekyll/jekyll/issues/3208
Ruby and windows were never in a good marriage :(

**Comment by prathamApp** [comment]
C:\RubyDevKit>gem install json
Fetching: json-2.1.0.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed json-2.1.0
Parsing documentation for json-2.1.0
Installing ri documentation for json-2.1.0
Done installing documentation for json after 1 seconds
1 gem installed

The above successfully installed the json.
But in case of dryrun, I think I should now drop all my weapons...:(
And yeah...I have Installed ruby installer and ruby devkit both of 64 bit.
